



/*
-- Query: SELECT * FROM tzfc_db.Tab_SellHouse
LIMIT 0, 1000

-- Date: 2016-01-22 15:00
*/
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);

INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('教工三村 (1室1厅1卫) 44㎡',1,1,1,44,44.00,10000,'',16,0,0,0,0,0,0,0,0,0,'','',NULL,'aaaa&aaaa\n\nsda\nds\n\na',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 水岸豪庭 (3室2厅2卫 毛胚) 222㎡',3,2,2,222,250.00,12000,'',9,5,4,6,1,1,2,1,1,2015,'XX小学','XX中学',NULL,'地段好；\n很牛逼的',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[其他地区] 东河阳光 (2室1厅1卫 中装) 88㎡',2,1,1,88,50.00,7999,'',10,7,1,5,0,3,2,1,0,0,'','',NULL,'',2);
INSERT INTO `Tab_SellHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`unit_price`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`rights_len`,`rights_type`,`rights_from`,`primary_school`,`junior_school`,`images`,`details`,`uid`) VALUES ('[城西] 财富广场 (1室1厅1卫 高装) 60㎡ 出售',1,1,1,60,30.00,5000,'',17,5,5,5,4,4,0,0,0,0,'','',NULL,'',2);



/*
-- Query: SELECT * FROM tzfc_db.Tab_RentHouse
LIMIT 0, 1000

-- Date: 2016-01-14 13:06
*/
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);

INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[其他地区] 供电新苑 (2室2厅2卫 毛胚) 222㎡ 出租',2,2,2,222,1999,2,0,NULL,'',24,7,0,0,1,1,2,'我们都是中国人',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[市区] 森园小区 (1室 简装) 50㎡ 出租',1,0,0,50,2000,1,8,NULL,'',13,1,-1,10,5,2,0,'地下一楼仓库',2);
INSERT INTO `Tab_RentHouse` (`title`,`rooms`,`halls`,`bathrooms`,`size`,`price`,`rent_type`,`rentpay_type`,`support_device`,`community`,`cid`,`aid`,`floors`,`floors_total`,`house_type`,`decor`,`orientation`,`details`,`uid`) VALUES ('[城中] 鹏欣丽都 (2室2厅2卫 中装) 100㎡ 出租',2,2,2,100,600,3,2,NULL,'',15,2,6,10,1,3,2,'床位出租啦~~~~',2);



